### ISSUE TITLE
IMDB List 100 movie limit.

### ISSUE THREAD

**Issue by jolbol1** [mza921/Plex-Auto-Collections#11]
An issue raised on vladmirs master was that an IMDB page maxes out at 100 movies and therefore so does the collection. A user there posted a fix for this in the IMDB tools by iterating over at least 10 pages. I upload the fix for that file [here](https://gist.github.com/jolbol1/b58afcd63edf7294985346c7f9ca857a).

Its just a for loop combing over 10 pages instead of just the first one. Seems to work.

**Comment by burkasaurusrex** [comment]
Agreed that the script should handle pagination automatically, but the fix linked above is a bit brittle. For example, it uses the `page` param which I believe only works with `list` pages, where the current script works with `search` pages as well. It also uses a fixed page size of 10 instead of detecting the pagination.

Until more robust pagination in supported, I've worked around it by adjusting the IMDb URLs. So, let's take this `list` page: `https://www.imdb.com/list/ls031310794` which is 64 titles long. The identical `search` page would be: `https://www.imdb.com/search/title/?lists=ls031310794`.

There's two options to solve it.

**1**. You could increase the length to the max length (250) by adding a `count=250` parameter: `https://www.imdb.com/search/title/?lists=ls031310794&count=250`.

**2**. Since this fork supports multiple lists per collection, you could also add links for each page:

```yaml
  Marvel Cinematic Universe:
    imdb-list:
      - https://www.imdb.com/search/title/?lists=ls031310794&start=1
      - https://www.imdb.com/search/title/?lists=ls031310794&start=51
    details:
      summary: >-
        The Marvel Cinematic Universe is a media franchise and shared
        universe centered on a series of superhero films, independently produced
        by Marvel Studios and based on characters that appear in American
        comic books published by Marvel Comics. The franchise includes comic
        books, short films, television series, and digital series. The shared
        universe, much like the original Marvel Universe in comic books, was
        established by crossing over common plot elements, settings, cast,
        and characters.
```

**Comment by meisnate12** [comment]
imdb lists and searches should work with multiple pages now without any work arounds this can be closed

**Comment by Jordan-Nelson** [comment]
Is there anyway to limit a search to n number of movies? For example, if I want to grab the top 10 feature films sorted by popularity?

**Comment by Jordan-Nelson** [comment]
It seems like adding `&count=n` to the url will get stripped out
