### ISSUE TITLE
Trakt list suddenly broke, not iterable

### ISSUE THREAD

**Issue by ExDominatus** [mza921/Plex-Auto-Collections#14]
I get the following error on a trakt list that used to work just fine previously:

`Traceback (most recent call last):
  File "plex_auto_collections.py", line 217, in <module>
    update_from_config(config_path, plex)
  File "/home/Ex/mza921/Plex-Auto-Collections/config_tools.py", line 125, in update_from_config
    missing = add_to_collection(config_path, plex, m, v, c, subfilters)
  File "/home/Ex/mza921/Plex-Auto-Collections/plex_tools.py", line 135, in add_to_collection
    movies, missing = trakt_tools.trakt_get_movies(config_path, plex, value)
  File "/home/Ex/mza921/Plex-Auto-Collections/trakt_tools.py", line 14, in trakt_get_movies
    title_ids = [m.pk[1] for m in trakt_list_items if isinstance(m, trakt.objects.movie.Movie)]
TypeError: 'NoneType' object is not iterable`

Anyone else have their trakt lists just break?

**Comment by burkasaurusrex** [comment]
Is the list that is causing problems public? Do you mind sharing?

I'd check to see if there was an item added to the list recently that might be causing problems.

**Comment by burkasaurusrex** [comment]
I just came across this error myself. My issue was that my Trakt token had expired. It worked without a problem once I deleted all the values under the `Authentication` key under `Trakt` key and then reauthenticated.

@mza921 might be worth adding some error handling on this API call (and any others)?

https://github.com/mza921/Plex-Auto-Collections/blob/4ef6d92173548944fb37cca41a079e2e0af67192/app/trakt_tools.py#L13

No idea if the Trakt library supports it or not, but it would be helpful if we surfaced the HTTP error instead of failing silently.

**Comment by pekempy** [comment]
RE trakt lists, the above fixed the issue for me, but it doesn't seem I can add multiple lists to one collection anymore?
For example 
`  DC Universe:
    trakt-list: https://trakt.tv/users/ljransom/lists/dc-universe-movies
    trakt-list: https://trakt.tv/users/arachn0id/lists/dc-extended-universe`

That used to check both lists and add them to one collection, it now only seems to take the first list

**Comment by burkasaurusrex** [comment]
Just wanted to clarify that the `yaml` should look like this:
```yaml
collections:
  DC Universe:
    trakt-list:
      - https://trakt.tv/users/ljransom/lists/dc-universe-movies
      - https://trakt.tv/users/arachn0id/lists/dc-extended-universe
```

**Comment by meisnate12** [comment]
can you test this with the new version to see if you still get this issue if not we can close this
