### ISSUE TITLE
[Feature Request] Case sensitivity and like constraints for poster or background matching

### ISSUE THREAD

**Issue by Tharic99** [mza921/Plex-Auto-Collections#177]
I've noticed that the poster or background image matching is rather severe in terms of what it's looking for. For instance, if a collection is named "DreamWorks" it's looking for a file named "DreamWorks.*" On a *nix system at least, that means that "dreamworks.*" fails to match.

In addition, many of the Actor/Director/Writer images that you get from theposterdb have (Acting) or (Directing) after the name, such as "Dwayne Johnson (Acting)". However the collection name would be "Dwayne Johnson" so the search is looking for "Dwayne Johnson.*" and it doesn't find "Dwayne Johnson (Actigin).png"

Could this be changed to a like%?

**Comment by BlueSkillZ99** [comment]
Case-sensitivity does not seem so crucial, I also stumbled over DreamWorks. But ignoring whole words is likely to create mismatches. e. g. 

Spider-Man 
Spider-Man: Spider-Verse
Spider-Man (Avengers)

**Comment by burkasaurusrex** [comment]
The exact match was intentional and I'm not sure would change. I would recommend looking at [poster](https://github.com/mza921/Plex-Auto-Collections#poster-collection-attribute) or [name mapping](https://github.com/mza921/Plex-Auto-Collections#name-mapping-collection-attribute) if you're hoping for the collection name to be different than the poster name.
