### ISSUE TITLE
To do: add Tautulli as a source

### ISSUE THREAD

**Issue by burkasaurusrex** [mza921/Plex-Auto-Collections#53]
See similar: https://github.com/bearlikelion/popularplex

**Comment by burkasaurusrex** [comment]
Other example: https://github.com/blacktwin/JBOPS/blob/master/fun/playlist_manager.py

**Comment by meisnate12** [comment]
so I've started working on this but we need to discuss 2 different things.

1. Theres a problem with how Tautulli creates the top/popular movie/show list. I've detailed it [here](https://github.com/bearlikelion/popularplex/issues/5) personally i want to go with the option of asking Tautulli for more movies and just stopping after a user given amount of tries.
2. We need to discuss how it will look in the config. Currently, my idea looks like below.
collections:
    Popular Movies:
        tautulli:
            type: popular          (This can be top or popular)
            duration: 30            (This is the number of days to look at what the popular movies/shows are)
            count: 20                (The number of shows to populate in the list)
            buffer: 50                (The number of shows to actually grab from Tautulli)

The buffer will cause the program to get more movies/shows than actually needed but it will only add up to the count. I can't think of a better way to overcome this problem aside from this weird workaround so if you have any ideas please let me know. I haven't really given much thought to the config names yet so let me know what you think we should do there too.

**Comment by meisnate12** [comment]
I've finished this it's on my master branch right now if you wanna test. It's going to be in the next pull request I make.

**Comment by mza921** [comment]
The variable names look good, but to be consistent with the tmdb enhancements you made, what if we used:
```
collections:
    Popular Movies:
        tautulli_popular:    (or tautulli_watched)
            list_days: 30
            list_size: 10
            list_buffer: 10
```
I'm working on something similar to support the Trakt trending list and I found it easier/consistent to add a method for `trakt_trending` instead of 
```
trakt_list:    (code is expecting a value here)
   list_type: trending    (would need `user` to be a default)
```

Does the buffer need to be defined by the user, or can it default to something based on the list_size?

**Comment by meisnate12** [comment]
i already had to put in a way for the add_to_collection method to pass in a library so giving them options should be relatively easy after my change which needs to happen anyways so the rest of tautulli's options can be there. I could separate tautulli into two different attributes but the reason i didn't is because it doesn't matter until its actually in the `get_tautullu` method and i would have been more work for me to constantly have if `m == "tautulli_popular" or m == "tautulli_watched"` vs `if m == "tautullu"`. 

If there were not other attributes that were needed i would have separated them into two separate attributes.

In terms of the `list_buffer` if you don't have the attribute or its invalid it will default to 10 but i wanted that number to be in the users hands just in case they needed it to be much bigger then the average user. 

You can view the README on my [branch](https://github.com/meisnate12/Plex-Auto-Collections#tautulli-list-list-type) for more detailed information on how i have it all set up

**Comment by meisnate12** [comment]
this can be closed
