### ISSUE TITLE
Request: Limit scan scope?

### ISSUE THREAD

**Issue by bigdork** [mza921/Plex-Auto-Collections#77]
You guys are doing awesome work and I'm genuinely thankful. I have setup and updated so many collections, but my libraries are so large it takes several hours to execute if I want to keep them updated. With +25K movies and +6.5K shows, running through creating Genre collections alone takes a couple hours. 

Is it possible to limit the scope of the script, ideally utilizing the "date added" attribute in Plex (or maybe Tautulli)? I'm not a programmer, but I envision running the script with a date option (-d 2020-10-20) or similar, which limits the script to execute against movies/shows added after the date given.

Thoughts?

**Comment by meisnate12** [comment]
in the next release there's a way to limit by originally released date but I don't know if it's going to be a whole lot faster for you because of how it works programmatically. My recommendation is to try and set up multiple scripts that can run operations concurrently or use tautulli to run a script anytime a new movie is added and have that script automatically add it to genre collections. and have our program run every once in a while to clean up anything thats been missed
